#端口
server:
  port: 8782

#eureka服务器地址
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

#eureka上服务的名字
spring:
  application:
    name=: SERVICE-FEIGN

#打开熔断器
feign:
  hystrix:
    enabled: true